openapi: 3.0.0
info:
  title: TaskMind API - Evaluations
  version: 1.0.0
  description: Endpoints para gestionar evaluaciones de estudiantes en TaskMind
servers:
  - url: http://localhost:4000
    description: Local server

paths:
  /api/evaluations/register:
    post:
      summary: Registra una nueva evaluación
      description: Crea una nueva evaluación en la base de datos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ID_COURSE:
                  type: integer
                  description: ID del curso asociado
                DSC_NAME:
                  type: string
                  description: Nombre de la evaluación
                WEIGHT:
                  type: number
                  format: double
                  description: Peso de la evaluación
                DATE_EVALUATION:
                  type: string
                  description: Fecha de la evaluación
                DSC_EVALUATION:
                  type: string
                  description: Descripción de la evaluación (opcional)
                ID_USER:
                  type: integer
                  description: ID del usuario que crea la evaluación
      responses:
        '200':
          description: Evaluación registrada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  evaluation:
                    $ref: '#/components/schemas/EvaluationType'
        '400':
          description: Campos incompletos o inválidos
        '500':
          description: Error interno del servidor

  /api/evaluations/search_evaluation:
    get:
      summary: Obtiene evaluaciones por ID de usuario
      description: Retorna las evaluaciones asociadas a un usuario específico
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '200':
          description: Lista de evaluaciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvaluationWithDetails'
        '204':
          description: No se encontraron evaluaciones
        '400':
          description: ID de usuario requerido
        '500':
          description: Error interno del servidor

  /api/evaluations/update_evaluation/{id}:
    put:
      summary: Actualiza una evaluación existente
      description: Modifica los datos de una evaluación
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la evaluación a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                DSC_NAME:
                  type: string
                  description: Nuevo nombre de la evaluación
                WEIGHT:
                  type: number
                  format: double
                  description: Nuevo peso de la evaluación
                DATE_EVALUATION:
                  type: string
                  description: Nueva fecha de evaluación
                DSC_EVALUATION:
                  type: string
                  description: Nueva descripción
      responses:
        '200':
          description: Evaluación actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  evaluation:
                    $ref: '#/components/schemas/EvaluationType'
        '404':
          description: Evaluación no encontrada
        '500':
          description: Error interno del servidor

components:
  schemas:
    EvaluationType:
      type: object
      properties:
        ID_TYPE:
          type: integer
        ID_COURSE:
          type: integer
        DSC_NAME:
          type: string
        WEIGHT:
          type: number
          format: double
        DATE_EVALUATION:
          type: string
        DSC_EVALUATION:
          type: string
        ID_USER:
          type: integer

    StudentEvaluation:
      type: object
      properties:
        ID_EVALUATION:
          type: integer
        ID_TYPE:
          type: integer
        SCORE_OBTAINED:
          type: number
          format: double
        DSC_COMMENT:
          type: string

    EvaluationWithDetails:
      type: object
      properties:
        ID_TYPE:
          type: integer
        ID_COURSE:
          type: integer
        DSC_NAME:
          type: string
        WEIGHT:
          type: number
          format: double
        DATE_EVALUATION:
          type: string
        DSC_EVALUATION:
          type: string
        ID_USER:
          type: integer
        Course:
          type: object
          properties:
            DSC_NAME:
              type: string
            DSC_CODE:
              type: string
        StudentEvaluations:
          type: array
          items:
            $ref: '#/components/schemas/StudentEvaluation'