openapi: 3.0.0
info:
  title: TaskMind API - Evaluations
  version: 1.0.0
  description: Endpoints para gestionar evaluaciones de estudiantes en TaskMind
servers:
  - url: http://localhost:4000
    description: Local server

paths:
  /api/evaluation/register:
    post:
      summary: Registra una nueva evaluación (tipo y resultado)
      description: Crea una nueva evaluación tipo y su resultado asociado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ID_COURSE:
                  type: integer
                  description: ID del curso asociado
                DSC_NAME:
                  type: string
                  description: Nombre de la evaluación
                WEIGHT:
                  type: number
                  format: double
                  description: Peso de la evaluación
                DATE_EVALUATION:
                  type: string
                  description: Fecha de la evaluación
                DSC_EVALUATION:
                  type: string
                  description: Descripción de la evaluación (opcional)
                ID_USER:
                  type: integer
                  description: ID del usuario que crea la evaluación
                SCORE_OBTAINED:
                  type: number
                  format: double
                  description: Puntaje obtenido
                DSC_COMMENT:
                  type: string
                  description: Comentario sobre el resultado (opcional)
      responses:
        '200':
          description: Evaluación registrada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  evaluationType:
                    $ref: '#/components/schemas/EvaluationType'
                  studentEvaluation:
                    $ref: '#/components/schemas/StudentEvaluation'
        '400':
          description: Campos incompletos o inválidos
        '500':
          description: Error interno del servidor

  /api/evaluation/search_evaluation:
    get:
      summary: Obtiene evaluaciones por ID de usuario
      description: Retorna las evaluaciones asociadas a un usuario específico con paginación
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: Identificación del usuario
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número de página
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          description: Tamaño de página
        - in: query
          name: orderByField
          schema:
            type: string
            default: "DATE_EVALUATION"
            enum:
              - DATE_EVALUATION
              - DSC_NAME
              - WEIGHT
          description: Campo para ordenar
        - in: query
          name: order
          schema:
            type: string
            default: "asc"
            enum:
              - asc
              - desc
          description: Dirección del orden
      responses:
        '200':
          description: Lista de evaluaciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
                  evaluations:
                    type: array
                    items:
                      $ref: '#/components/schemas/EvaluationWithDetails'
        '204':
          description: No se encontraron evaluaciones
        '400':
          description: ID de usuario requerido
        '500':
          description: Error interno del servidor

  /api/evaluation/update_evaluation/{id}:
    put:
      summary: Actualiza una evaluación existente (tipo o resultado)
      description: Modifica los datos de una evaluación tipo o su resultado
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la evaluación a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/EvaluationTypeUpdate'
                - $ref: '#/components/schemas/StudentEvaluationUpdate'
      responses:
        '200':
          description: Evaluación actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  evaluation:
                    oneOf:
                      - $ref: '#/components/schemas/EvaluationType'
                      - $ref: '#/components/schemas/StudentEvaluation'
        '400':
          description: Datos inválidos o no coinciden con ningún formato
        '404':
          description: Evaluación no encontrada
        '500':
          description: Error interno del servidor

components:
  schemas:
    EvaluationType:
      type: object
      properties:
        ID_TYPE:
          type: integer
        ID_COURSE:
          type: integer
        DSC_NAME:
          type: string
        WEIGHT:
          type: number
          format: double
        DATE_EVALUATION:
          type: string
        DSC_EVALUATION:
          type: string
        ID_USER:
          type: integer

    StudentEvaluation:
      type: object
      properties:
        ID_EVALUATION:
          type: integer
        ID_TYPE:
          type: integer
        SCORE_OBTAINED:
          type: number
          format: double
        DSC_COMMENT:
          type: string

    EvaluationWithDetails:
      type: object
      properties:
        ID_TYPE:
          type: integer
        ID_COURSE:
          type: integer
        DSC_NAME:
          type: string
        WEIGHT:
          type: number
          format: double
        DATE_EVALUATION:
          type: string
        DSC_EVALUATION:
          type: string
        ID_USER:
          type: integer
        Course:
          type: object
          properties:
            DSC_NAME:
              type: string
            DSC_CODE:
              type: string
        StudentEvaluations:
          type: array
          items:
            $ref: '#/components/schemas/StudentEvaluation'
        User:
          type: object
          properties:
            DSC_FIRST_NAME:
              type: string
            DSC_LAST_NAME_ONE:
              type: string

    EvaluationTypeUpdate:
      type: object
      properties:
        ID_COURSE:
          type: integer
        DSC_NAME:
          type: string
        WEIGHT:
          type: number
          format: double
        DATE_EVALUATION:
          type: string
        DSC_EVALUATION:
          type: string
        ID_USER:
          type: integer
      required:
        - ID_COURSE
        - DSC_NAME
        - WEIGHT
        - DATE_EVALUATION
        - ID_USER

    StudentEvaluationUpdate:
      type: object
      properties:
        ID_TYPE:
          type: integer
        SCORE_OBTAINED:
          type: number
          format: double
        DSC_COMMENT:
          type: string
      required:
        - ID_TYPE
        - SCORE_OBTAINED