openapi: 3.0.0
info:
  title: TaskMind API - Home Page
  version: 1.0.0
  description: >
    Endpoint para la página de inicio del estudiante.
    Devuelve resumen de cursos y próximas evaluaciones.

servers:
  - url: http://localhost:4000
    description: Servidor local de desarrollo

paths:
  /api/home-page/getHomePage:
    get:
      summary: Página de inicio del estudiante
      description: >
        Retorna el resumen de cursos (total, aprobados, pendientes) y
        las 3 evaluaciones más próximas que aún no han ocurrido.
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: Número de cédula del estudiante
      responses:
        "200":
          description: Datos cargados exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  resumenCursos:
                    type: object
                    properties:
                      TotalCursos:
                        type: integer
                        example: 5
                      Aprobados:
                        type: integer
                        example: 3
                      Pendientes:
                        type: integer
                        example: 2
                  evaluacionesProximas:
                    type: array
                    items:
                      type: object
                      properties:
                        ID_TYPE:
                          type: integer
                          example: 7
                        NombreEvaluacion:
                          type: string
                          example: "Examen Parcial"
                        FechaEvaluacion:
                          type: string
                          format: date-time
                          example: "2025-07-01T00:00:00.000Z"
                        Detalle:
                          type: string
                          example: "Evaluación de mitad de curso"
                        Curso:
                          type: string
                          example: "Inglés"
        "204":
          description: No se encontró información para la cédula indicada
        "400":
          description: El parámetro userId es requerido
        "500":
          description: Error interno del servidor
