openapi: 3.0.0
info:
  title: User API
  description: API para el registro y actualización de usuarios
  version: 1.0.0

paths:
  /api/Auth/loginAccess:
    post:
      summary: Iniciar sesión de usuario
      description: Autentica a un usuario utilizando su correo electrónico y contraseña.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                DSC_EMAIL:
                  type: string
                  example: "juan.perez@example.com"
                DSC_PASSWORD:
                  type: string
                  example: "securePassword123"
              required:
                - DSC_EMAIL
                - DSC_PASSWORD
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID_USER:
                    type: integer
                  DSC_FIRST_NAME:
                    type: string
                  DSC_LAST_NAME_ONE:
                    type: string
                  DSC_EMAIL:
                    type: string
                  DSC_CAREER:
                    type: string
                  message:
                    type: string
                    example: "Bienvenido de nuevo, Juan!"
        '400':
          description: Error de autenticación, correo electrónico o contraseña incorrectos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                    example: ["Error al procesar la solicitud"]
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
